// Generated by res/make_game_db.py from res/games.tsv. Do not edit.
#pragma once

struct GameDbEntry {
  unsigned crc;
  const char *name, *region, *type, *tier, *flags, *notes;
};

inline constexpr GameDbEntry kGameDb[] = {
    {0xdb36283fu, "1st Grade", "USA", "Cartridge", "In-game", "", ""},
    {0xaf063ba4u, "Animal Genius", "USA", "Cartridge", "In-game", "", ""},
    {0x5d4f7cd0u, "Bratz World - The Jet Set", "USA", "Cartridge", "In-game", "", ""},
    {0xc7b62602u, "Cars", "Germany", "Cartridge", "In-game", "", ""},
    {0xd4a7e5d4u, "Cars", "USA", "Cartridge", "In-game", "", ""},
    {0xbeca3909u, "Cars - Supercharged", "USA", "Cartridge", "In-game", "", ""},
    {0x0134af49u, "Clifford - The Big Red Dog - Reading", "USA", "Cartridge", "In-game", "", ""},
    {0x979346d5u, "Cosmic Math - Arcade-Style Learning!", "USA", "Cartridge", "In-game", "", ""},
    {0x9f08d02au, "Creature Create", "USA", "Cartridge", "In-game", "", ""},
    {0x71062cd7u, "Demo - Herbst 2004 II", "Germany", "Cartridge", "In-game", "", ""},
    {0x822ca3dau, "Digging for Dinosaurs", "USA", "Cartridge", "In-game", "", ""},
    {0x8a605512u, "Disney Fairies", "USA", "Cartridge", "In-game", "", ""},
    {0x5ccb2ad3u, "Disney Princess", "USA", "Cartridge", "In-game", "", ""},
    {0x2465f01du, "Disney Princess - Worlds of Enchantment", "USA", "Cartridge", "In-game", "", ""},
    {0xbb6d5375u, "Disney Prinzessinnen - Zauberhaftes Lernen", "Germany", "Cartridge", "In-game", "", ""},
    {0x242907d4u, "Dora - Retter der Wildnis", "Germany", "Cartridge", "In-game", "", ""},
    {0x71778536u, "Dora the Explorer - Camping Adventure", "USA", "Cartridge", "In-game", "", ""},
    {0x6a5e20bau, "Findet Nemo", "Germany", "Cartridge", "In-game", "", ""},
    {0x1895f946u, "Finding Nemo", "USA", "Cartridge", "In-game", "", ""},
    {0xe62d1684u, "Foster's Home for Imaginary Friends", "USA", "Cartridge", "In-game", "", ""},
    {0x05b608f0u, "Get Puzzled!", "USA", "Cartridge", "In-game", "", ""},
    {0xebbf83a0u, "Go Diego Go! - Animal Rescuer", "USA", "Cartridge", "In-game", "", ""},
    {0x6fd44f1au, "Grundschule 1", "Germany", "Cartridge", "In-game", "", ""},
    {0x96d30f93u, "Grundschule 2 - Musik in Gefahr", "Germany", "Cartridge", "In-game", "", ""},
    {0x7c716016u, "I Spy - Treasure Hunt", "USA", "Cartridge", "In-game", "", ""},
    {0xdb262164u, "Kindergarten", "USA", "Cartridge", "In-game", "", ""},
    {0xe1f505e7u, "Lernen mit Leap", "Germany", "Cartridge", "In-game", "", ""},
    {0x9d1c2f35u, "Letter Factory", "USA", "Cartridge", "In-game", "", ""},
    {0xa9c75d90u, "Madagascar", "USA", "Cartridge", "In-game", "", ""},
    {0xfe8bd3fdu, "Math Baseball", "USA", "Cartridge", "In-game", "", ""},
    {0xe58eac06u, "Mit Bruno Bleistift lernst du Malen & Schreiben", "Germany", "Cartridge", "In-game", "", ""},
    {0xdbb767ccu, "Mr. Pencil's Learn to Draw & Write", "USA", "Cartridge", "In-game", "", ""},
    {0x2fc77c9du, "My Amusement Park", "USA", "Cartridge", "In-game", "", ""},
    {0x01f12ce7u, "Numbers on the Run", "USA", "Cartridge", "In-game", "", ""},
    {0x3c428a13u, "Pet Pals", "USA", "Cartridge", "In-game", "", ""},
    {0xdf729fe7u, "Ratatouille", "Germany", "Cartridge", "In-game", "", ""},
    {0xd0c4de47u, "Ratatouille", "USA", "Cartridge", "In-game", "", ""},
    {0x2c6e623eu, "Reading with Phonics - Mole's Huge Nose", "USA", "Cartridge", "In-game", "", ""},
    {0x43bb0b63u, "Schoolhouse Rock - America Rock", "USA", "Cartridge", "In-game", "unsigned", ""},
    {0x53c9d9b2u, "Schoolhouse Rock - Grammar Rock", "USA", "Cartridge", "In-game", "", ""},
    {0xa9d2cdbdu, "Sonic X", "USA", "Cartridge", "In-game", "", ""},
    {0x9dc2e5f6u, "Spider-Man - Schachmatt den Schildersaboteuren!", "Germany", "Cartridge", "In-game", "", ""},
    {0x0ef61cbbu, "Spider-Man - The Case Of The Sinister Speller", "USA", "Cartridge", "In-game", "", ""},
    {0x8761fc61u, "Spongebob Schwammkopf - Zeitreise durch das Wurmloch", "Germany", "Cartridge", "In-game", "", ""},
    {0xd11e7c30u, "Spongebob Schwammkopf hat alles im Griff", "Germany", "Cartridge", "In-game", "", ""},
    {0x0f2ad725u, "Spongebob Squarepants - Saves the Day", "USA", "Cartridge", "In-game", "", ""},
    {0x27000674u, "Star Wars - Jedi Math", "USA", "Cartridge", "In-game", "", ""},
    {0xce9ce136u, "Tangled", "USA", "Cartridge", "In-game", "", ""},
    {0xde5fb26eu, "The Backyardigans", "USA", "Cartridge", "In-game", "", ""},
    {0xa0a362aau, "The Batman - Multipliziere, Dividiere und Regiere", "Germany", "Cartridge", "In-game", "", ""},
    {0x7c934681u, "The Batman - Strength in Numbers", "USA", "Cartridge", "In-game", "", ""},
    {0xd8ac1a09u, "The Disney-Pixar Collection", "USA", "Cartridge", "In-game", "", ""},
    {0x076ad299u, "The Penguins of Madagascar", "USA", "Cartridge", "In-game", "", ""},
    {0x5303d366u, "Thomas & Friends - Calling All Engines!", "USA", "Cartridge", "In-game", "", ""},
    {0xa72c61fdu, "Toy Story 3", "USA", "Cartridge", "In-game", "", ""},
    {0x1e2a5031u, "Up", "USA", "Cartridge", "In-game", "", ""},
    {0x4c5e775eu, "Vorschule", "Germany", "Cartridge", "In-game", "", ""},
    {0xee2c39eau, "Wall-E", "Germany", "Cartridge", "In-game", "", ""},
    {0x75164c8eu, "Weltraum-Mathe - Lernen im Arcade-Stil!", "Germany", "Cartridge", "In-game", "", ""},
    {0xa707de61u, "Woerterjaeger - Lernen im Arcade-Stil!", "Germany", "Cartridge", "In-game", "", ""},
    {0x67bd4a6au, "Wolverine and the X-Men", "USA", "Cartridge", "In-game", "", ""},
    {0x334ab5d0u, "Zahlenjaeger - Lernen im Arcade-Stil!", "Germany", "Cartridge", "In-game", "", ""},
    {0x3ba2351du, "Cars (prototype, July 26 2005)", "USA", "Prototype", "In-game", "", ""},
    {0x175d575fu, "Cars Supercharged (prototype, January 10 2007)", "USA", "Prototype", "In-game", "dev-upload", ""},
    {0x28b9d48bu, "Go Diego Go Animal Rescuer (prototype, April 5 2007)", "USA", "Prototype", "In-game", "", ""},
    {0x791e7f08u, "Go Diego Go Animal Rescuer (prototype, March 15 2007)", "USA", "Prototype", "In-game", "dev-upload", ""},
    {0xfe8b39f9u, "Pet Pals (prototype, October 17 2006)", "USA", "Prototype", "In-game", "dev-upload", ""},
    {0x2c247582u, "Wall-E (prototype, December 20 2007)", "USA", "Prototype", "In-game", "", ""},
    {0xb0f756d3u, "Chicken Coop", "USA", "Download", "In-game", "stub-services", ""},
    {0xc1cccd8cu, "Disney Fairies Demo", "USA", "Download", "In-game", "", ""},
    {0x6efa1565u, "Disney Pixar UP Demo", "USA", "Download", "In-game", "", ""},
    {0x7c630b95u, "Disney The Princess and the Frog Demo", "USA", "Download", "In-game", "", ""},
    {0xbd207967u, "Disney-Pixar Toy Story 3 Mini-Game", "USA", "Download", "In-game", "", ""},
    {0xe0410d99u, "Dragons to the Rescue", "USA", "Download", "In-game", "", ""},
    {0x08061079u, "Letterpillar", "USA", "Download", "In-game", "stub-services", ""},
    {0xf78d3848u, "Ni Hao, Kai-lan Demo", "USA", "Download", "In-game", "", ""},
    {0x60f09e5bu, "Number Raiders", "USA", "Download", "In-game", "stub-services", ""},
    {0xbec0f4b4u, "Rabbit River", "USA", "Download", "In-game", "stub-services", ""},
    {0xd0a37eb2u, "Shape Shop", "USA", "Download", "In-game", "stub-services", ""},
    {0xa609e614u, "Star Wars: Jedi Reading Demo", "USA", "Download", "In-game", "", ""},
    {0x614539e7u, "Wolverine & the X-Men Demo", "USA", "Download", "In-game", "", ""},
};

// Whether a comma-separated flags list (GameDbEntry::flags) has `flag`.
inline bool game_db_flag(const char* flags, const char* flag) {
  for (const char* p = flags; *p;) {
    const char* f = flag;
    while (*f && *p == *f) p++, f++;
    if (!*f && (!*p || *p == ',')) return true;
    while (*p && *p != ',') p++;
    if (*p) p++;
  }
  return false;
}

// The flags of the image with this CRC, if the database knows it.
inline bool game_db_has_flag(unsigned crc, const char* flag) {
  for (const GameDbEntry& d : kGameDb)
    if (d.crc == crc) return game_db_flag(d.flags, flag);
  return false;
}
