#!/usr/bin/env python3
# Turns res/games.tsv into src/gui/game_db.h (the game list's database) and the
# tables of docs/compatibility.md (between its "games:" markers). Run from the
# repository root after editing res/games.tsv.
import re

rows = []
# Compatibility ratings, from worst to best, and their squares (filled: how far it gets).
TIERS = ["Untested", "Broken", "Intro", "Menus", "In-game"]
SQUARES = {t: "\u25a0" * i + "\u25a1" * (5 - i) for i, t in enumerate(TIERS)}

for line in open("res/games.tsv", encoding="utf-8"):
    if line.startswith("#") or not line.strip():
        continue
    f = line.rstrip("\n").split("\t")
    f += [""] * (8 - len(f))
    rows.append(dict(crc=f[0], name=f[1], region=f[2], type=f[3], tier=f[4], flags=f[5], internal=f[6], notes=f[7]))
    for flag in filter(None, f[5].split(",")):
        if flag not in ("unsigned", "stub-services", "dev-upload"):
            raise SystemExit(f"res/games.tsv: {f[1]}: unknown flag {flag!r}")
    if f[4] not in TIERS:
        raise SystemExit(f"res/games.tsv: {f[1]}: unknown compatibility {f[4]!r} (one of {', '.join(TIERS)})")

def c(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'

with open("src/gui/game_db.h", "w", encoding="utf-8") as out:
    out.write("// Generated by res/make_game_db.py from res/games.tsv. Do not edit.\n#pragma once\n\n")
    out.write("struct GameDbEntry {\n  unsigned crc;\n  const char *name, *region, *type, *tier, *flags, *notes;\n};\n\n")
    out.write("inline constexpr GameDbEntry kGameDb[] = {\n")
    for r in rows:
        out.write(f"    {{0x{r['crc']}u, {c(r['name'])}, {c(r['region'])}, {c(r['type'])}, {c(r['tier'])}, {c(r['flags'])}, {c(r['notes'])}}},\n")
    out.write("};\n\n")
    out.write("""// Whether a comma-separated flags list (GameDbEntry::flags) has `flag`.
inline bool game_db_flag(const char* flags, const char* flag) {
  for (const char* p = flags; *p;) {
    const char* f = flag;
    while (*f && *p == *f) p++, f++;
    if (!*f && (!*p || *p == ',')) return true;
    while (*p && *p != ',') p++;
    if (*p) p++;
  }
  return false;
}

// The flags of the image with this CRC, if the database knows it.
inline bool game_db_has_flag(unsigned crc, const char* flag) {
  for (const GameDbEntry& d : kGameDb)
    if (d.crc == crc) return game_db_flag(d.flags, flag);
  return false;
}
""")

# The fixes leapemu applies by itself (explained in docs/compatibility.md,
# "Fixes leapemu applies by itself"): each game's, at the start of its notes.
FIXES = {"unsigned": "Fix: [content checks skipped](#content-checks-skipped)",
         "stub-services": "Fix: [Leapster 2 services](#leapster-2-services)",
         "dev-upload": "Fix: [block headers removed](#development-uploads)"}
def fixes(r):
    return ", ".join(FIXES[f] for f in filter(None, r["flags"].split(",")))

sections = [("Cartridge", "Cartridges", True), ("Prototype", "Prototypes", True), ("Download", "Leapster 2 downloadable games", False)]
md = []
for typ, title, with_region in sections:
    md.append(f"## {title}\n")
    if typ == "Download":
        md.append("Run on the Leapster's own BaseROM, each [loaded as on a Leapster 2](#leapster-2-downloads);\n"
                  "see [downloadables.md](downloadables.md).\n")
    md.append("| Title | Region | Tier | Notes |\n|---|---|---|---|" if with_region else "| Title | Tier | Notes |\n|---|---|---|")
    for r in rows:
        if r["type"] != typ:
            continue
        # The notes: any fix leapemu applies by itself first, then the database's notes.
        notes = "; ".join(filter(None, [fixes(r), r["notes"].strip()]))
        tier = SQUARES[r["tier"]] + " " + r["tier"]
        cells = [r["name"], r["region"], tier, notes] if with_region else [r["name"], tier, notes]
        md.append("| " + " | ".join(cells) + " |")
    md.append("")
doc = open("docs/compatibility.md", encoding="utf-8").read()
begin, end = "<!-- games:begin (generated from res/games.tsv) -->", "<!-- games:end -->"
new = begin + "\n\n" + "\n".join(md) + "\n" + end
doc = re.sub(re.escape(begin) + ".*?" + re.escape(end), lambda m: new, doc, flags=re.S)
open("docs/compatibility.md", "w", encoding="utf-8").write(doc)
print(f"{len(rows)} games")
