#!/usr/bin/env python3
# Regenerates src/gui/icon.h (the window icon, 64x64 RGBA) from res/leapemu.svg.
# Needs rsvg-convert (librsvg). Run from the repository root.
import struct, subprocess, zlib

SIZE = 64
png = subprocess.run(["rsvg-convert", "-w", str(SIZE), "-h", str(SIZE), "res/leapemu.svg"],
                     check=True, capture_output=True).stdout

# Decode the (8-bit RGBA, non-interlaced) PNG rsvg-convert writes.
pos, idat, width, height = 8, b"", 0, 0
while pos < len(png):
    n, kind = struct.unpack(">I4s", png[pos:pos + 8])
    data = png[pos + 8:pos + 8 + n]
    if kind == b"IHDR":
        width, height, depth, ctype = struct.unpack(">IIBB", data[:10])
        assert depth == 8 and ctype == 6, "expected 8-bit RGBA"
    elif kind == b"IDAT":
        idat += data
    pos += 12 + n
raw, stride, rows, prev = zlib.decompress(idat), width * 4, [], bytearray(width * 4)
for y in range(height):
    f, line = raw[y * (stride + 1)], bytearray(raw[y * (stride + 1) + 1:(y + 1) * (stride + 1)])
    for i in range(stride):
        a = line[i - 4] if i >= 4 else 0
        b = prev[i]
        c = prev[i - 4] if i >= 4 else 0
        if f == 1: line[i] = (line[i] + a) & 255
        elif f == 2: line[i] = (line[i] + b) & 255
        elif f == 3: line[i] = (line[i] + (a + b) // 2) & 255
        elif f == 4:
            p = a + b - c
            pa, pb, pc = abs(p - a), abs(p - b), abs(p - c)
            line[i] = (line[i] + (a if pa <= pb and pa <= pc else b if pb <= pc else c)) & 255
    rows.append(line)
    prev = line
pixels = b"".join(rows)

with open("src/gui/icon.h", "w") as out:
    out.write("// Generated by res/make_icon.py from res/leapemu.svg: the window icon,\n")
    out.write(f"// {SIZE}x{SIZE} pixels, RGBA (bytes R, G, B, A). Do not edit.\n#pragma once\n\n")
    out.write(f"constexpr int kIconSize = {SIZE};\n")
    out.write("constexpr unsigned char kIconRgba[] = {\n")
    for i in range(0, len(pixels), 24):
        out.write("    " + ",".join(str(v) for v in pixels[i:i + 24]) + ",\n")
    out.write("};\n")
